import {CartProvider} from '@/context/cartContext';
import Navbar from '@/components/navbar';
import './globals.css';
import Footer from '@/components/footer';

export const metadata = {
 title: 'Coffee House',
 description: 'Generated by vvebanextgen',
};

export default function RootLayout({children}) {
 return (
  <html lang="en">
   <head>
    <link
     rel="stylesheet"
     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
     href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Josefin+Sans:wght@300;400;700&family=Poppins:wght@300;400;700&display=swap"
     rel="stylesheet"
    />
   </head>

   <body>
     <div className="container">
    <CartProvider>
      <Navbar />
      {children}
      <Footer />
    </CartProvider>
     </div>
   </body>
  </html>
 );
}
